// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class BookingHistoryDatLt
{
    public int HistoryDatLtId { get; set; }

    public int BookingTuTtcId { get; set; }

    public string Action { get; set; }

    public int ActionBy { get; set; }

    public DateTime ActionTime { get; set; }

    public string OldStatus { get; set; }

    public string NewStatus { get; set; }

    public string Reason { get; set; }

    public bool? IsSystemAction { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User ActionByNavigation { get; set; }

    public virtual BookingTuTtc BookingTuTtc { get; set; }
}