// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class BookingTuTtc
{
    public int BookingTuTtcId { get; set; }

    public int UserId { get; set; }

    public int FacilityUnitKietNtId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public bool? ConflictFlag { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<BookingHistoryDatLt> BookingHistoryDatLts { get; set; } = new List<BookingHistoryDatLt>();

    public virtual FacilityUnitKietNt FacilityUnitKietNt { get; set; }

    public virtual User User { get; set; }
}