// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class CampusThanhDt
{
    public int CampusThanhDtid { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<FacilityThanhDt> FacilityThanhDts { get; set; } = new List<FacilityThanhDt>();
}