// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class FacilityUnitKietNt
{
    public int FacilityUnitKietNtId { get; set; }

    public int FacilityThanhDtid { get; set; }

    public string UnitName { get; set; }

    public int? Capacity { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsActive { get; set; }

    public bool? RequiresApproval { get; set; }

    public DateTime? LastMaintenanceDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<BookingTuTtc> BookingTuTtcs { get; set; } = new List<BookingTuTtc>();

    public virtual ICollection<FacilitySchedulePhatNth> FacilitySchedulePhatNths { get; set; } = new List<FacilitySchedulePhatNth>();

    public virtual FacilityThanhDt FacilityThanhDt { get; set; }

    public virtual ICollection<MaintenanceRequestMinhTq> MaintenanceRequestMinhTqs { get; set; } = new List<MaintenanceRequestMinhTq>();

    public virtual ICollection<UsageReportHuyDk> UsageReportHuyDks { get; set; } = new List<UsageReportHuyDk>();
}