// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class FacilityTypeThanhDt
{
    public int FacilityTypeThanhDtid { get; set; }

    public string TypeName { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string Description { get; set; }

    public virtual ICollection<FacilityThanhDt> FacilityThanhDts { get; set; } = new List<FacilityThanhDt>();
}