// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class FacilitySchedulePhatNth
{
    public int SchedulePhatNthId { get; set; }

    public int FacilityUnitKietNtId { get; set; }

    public DateOnly ScheduleDate { get; set; }

    public TimeOnly OpenTime { get; set; }

    public TimeOnly CloseTime { get; set; }

    public bool? IsClosed { get; set; }

    public string Reason { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual FacilityUnitKietNt FacilityUnitKietNt { get; set; }
}