// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class FacilityThanhDt
{
    public int FacilityThanhDtid { get; set; }

    public string FacilityName { get; set; }

    public int FacilityTypeThanhDtid { get; set; }

    public int CampusThanhDtid { get; set; }

    public int Capacity { get; set; }

    public string LocationDetail { get; set; }

    public string Description { get; set; }

    public bool? IsAvailable { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CampusThanhDt CampusThanhDt { get; set; }

    public virtual FacilityTypeThanhDt FacilityTypeThanhDt { get; set; }

    public virtual ICollection<FacilityUnitKietNt> FacilityUnitKietNts { get; set; } = new List<FacilityUnitKietNt>();
}