// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class MaintenanceRequestMinhTq
{
    public int RequestMinhTqId { get; set; }

    public int FacilityUnitKietNtId { get; set; }

    public int ReportedBy { get; set; }

    public string IssueDescription { get; set; }

    public int? SeverityLevel { get; set; }

    public DateTime RequestTime { get; set; }

    public DateTime? ResolvedTime { get; set; }

    public bool? IsResolved { get; set; }

    public string TechnicianNote { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual FacilityUnitKietNt FacilityUnitKietNt { get; set; }

    public virtual User ReportedByNavigation { get; set; }
}