// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class UsageReportHuyDk
{
    public int ReportId { get; set; }

    public int FacilityUnitKietNtId { get; set; }

    public int? TotalBookings { get; set; }

    public int? UsageHours { get; set; }

    public double? UsageRate { get; set; }

    public string ReportPeriod { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int GeneratedBy { get; set; }

    public string Note { get; set; }

    public bool? IsFinal { get; set; }

    public virtual FacilityUnitKietNt FacilityUnitKietNt { get; set; }

    public virtual User GeneratedByNavigation { get; set; }
}