// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CFB.Entities.ThanhDT.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public int RoleId { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BookingHistoryDatLt> BookingHistoryDatLts { get; set; } = new List<BookingHistoryDatLt>();

    public virtual ICollection<BookingTuTtc> BookingTuTtcs { get; set; } = new List<BookingTuTtc>();

    public virtual ICollection<FacilitySchedulePhatNth> FacilitySchedulePhatNths { get; set; } = new List<FacilitySchedulePhatNth>();

    public virtual ICollection<MaintenanceRequestMinhTq> MaintenanceRequestMinhTqs { get; set; } = new List<MaintenanceRequestMinhTq>();

    public virtual Role Role { get; set; }

    public virtual ICollection<UsageReportHuyDk> UsageReportHuyDks { get; set; } = new List<UsageReportHuyDk>();
}