// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CFB.Entities.ThanhDT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

//namespace CFB.Entities.ThanhDT.Models;
namespace CFB.Repositories.ThanhDT.DBContext;
public partial class FA25_PRN222_3W_G2_CampusFacilityBookingContext : DbContext
{
    public FA25_PRN222_3W_G2_CampusFacilityBookingContext()
    {
    }

    public FA25_PRN222_3W_G2_CampusFacilityBookingContext(DbContextOptions<FA25_PRN222_3W_G2_CampusFacilityBookingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BookingHistoryDatLt> BookingHistoryDatLts { get; set; }

    public virtual DbSet<BookingTuTtc> BookingTuTtcs { get; set; }

    public virtual DbSet<CampusThanhDt> CampusThanhDts { get; set; }

    public virtual DbSet<FacilitySchedulePhatNth> FacilitySchedulePhatNths { get; set; }

    public virtual DbSet<FacilityThanhDt> FacilityThanhDts { get; set; }

    public virtual DbSet<FacilityTypeThanhDt> FacilityTypeThanhDts { get; set; }

    public virtual DbSet<FacilityUnitKietNt> FacilityUnitKietNts { get; set; }

    public virtual DbSet<MaintenanceRequestMinhTq> MaintenanceRequestMinhTqs { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<UsageReportHuyDk> UsageReportHuyDks { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=HP-VICTUSNKV;Initial Catalog=FA25_PRN222_3W_G2_CampusFacilityBooking;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");
    // Ctrl + K + C để comment
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BookingHistoryDatLt>(entity =>
        {
            entity.HasKey(e => e.HistoryDatLtId).HasName("PK__BookingH__2061707B3F95B355");

            entity.ToTable("BookingHistoryDatLT");

            entity.Property(e => e.HistoryDatLtId).HasColumnName("historyDatLT_id");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("action");
            entity.Property(e => e.ActionBy).HasColumnName("action_by");
            entity.Property(e => e.ActionTime)
                .HasColumnType("datetime")
                .HasColumnName("action_time");
            entity.Property(e => e.BookingTuTtcId).HasColumnName("bookingTuTTC_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.IsSystemAction)
                .HasDefaultValue(false)
                .HasColumnName("is_system_action");
            entity.Property(e => e.NewStatus)
                .HasMaxLength(50)
                .HasColumnName("new_status");
            entity.Property(e => e.OldStatus)
                .HasMaxLength(50)
                .HasColumnName("old_status");
            entity.Property(e => e.Reason).HasColumnName("reason");

            entity.HasOne(d => d.ActionByNavigation).WithMany(p => p.BookingHistoryDatLts)
                .HasForeignKey(d => d.ActionBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingHi__actio__5CD6CB2B");

            entity.HasOne(d => d.BookingTuTtc).WithMany(p => p.BookingHistoryDatLts)
                .HasForeignKey(d => d.BookingTuTtcId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingHi__booki__5BE2A6F2");
        });

        modelBuilder.Entity<BookingTuTtc>(entity =>
        {
            entity.HasKey(e => e.BookingTuTtcId).HasName("PK__BookingT__999A0A2173AA4355");

            entity.ToTable("BookingTuTTC", tb => tb.HasTrigger("trg_Booking_Update"));

            entity.Property(e => e.BookingTuTtcId).HasColumnName("bookingTuTTC_id");
            entity.Property(e => e.ConflictFlag)
                .HasDefaultValue(false)
                .HasColumnName("conflict_flag");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("end_time");
            entity.Property(e => e.FacilityUnitKietNtId).HasColumnName("facilityUnitKietNT_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.StartTime)
                .HasColumnType("datetime")
                .HasColumnName("start_time");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.FacilityUnitKietNt).WithMany(p => p.BookingTuTtcs)
                .HasForeignKey(d => d.FacilityUnitKietNtId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingTu__facil__5629CD9C");

            entity.HasOne(d => d.User).WithMany(p => p.BookingTuTtcs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingTu__user___5535A963");
        });

        modelBuilder.Entity<CampusThanhDt>(entity =>
        {
            entity.HasKey(e => e.CampusThanhDtid).HasName("PK__CampusTh__44E57CF8D508B21A");

            entity.ToTable("CampusThanhDT");

            entity.Property(e => e.CampusThanhDtid).HasColumnName("campusThanhDTID");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("createDate");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("datetime")
                .HasColumnName("updateDate");
        });

        modelBuilder.Entity<FacilitySchedulePhatNth>(entity =>
        {
            entity.HasKey(e => e.SchedulePhatNthId).HasName("PK__Facility__7FDC44C066D6ADF9");

            entity.ToTable("FacilitySchedulePhatNTH", tb => tb.HasTrigger("trg_Schedule_Update"));

            entity.Property(e => e.SchedulePhatNthId).HasColumnName("schedulePhatNTH_id");
            entity.Property(e => e.CloseTime).HasColumnName("close_time");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.FacilityUnitKietNtId).HasColumnName("facilityUnitKietNT_id");
            entity.Property(e => e.IsClosed)
                .HasDefaultValue(false)
                .HasColumnName("is_closed");
            entity.Property(e => e.OpenTime).HasColumnName("open_time");
            entity.Property(e => e.Reason).HasColumnName("reason");
            entity.Property(e => e.ScheduleDate).HasColumnName("schedule_date");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.FacilitySchedulePhatNths)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FacilityS__creat__6EF57B66");

            entity.HasOne(d => d.FacilityUnitKietNt).WithMany(p => p.FacilitySchedulePhatNths)
                .HasForeignKey(d => d.FacilityUnitKietNtId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FacilityS__facil__6E01572D");
        });

        modelBuilder.Entity<FacilityThanhDt>(entity =>
        {
            entity.HasKey(e => e.FacilityThanhDtid).HasName("PK__Facility__B412D4CDDC962824");

            entity.ToTable("FacilityThanhDT", tb => tb.HasTrigger("trg_Facility_Update"));

            entity.Property(e => e.FacilityThanhDtid).HasColumnName("facilityThanhDTID");
            entity.Property(e => e.CampusThanhDtid).HasColumnName("campusThanhDTID");
            entity.Property(e => e.Capacity).HasColumnName("capacity");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.FacilityName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("facility_name");
            entity.Property(e => e.FacilityTypeThanhDtid).HasColumnName("facilityTypeThanhDTID");
            entity.Property(e => e.IsAvailable)
                .HasDefaultValue(true)
                .HasColumnName("is_available");
            entity.Property(e => e.LocationDetail)
                .HasMaxLength(255)
                .HasColumnName("location_detail");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CampusThanhDt).WithMany(p => p.FacilityThanhDts)
                .HasForeignKey(d => d.CampusThanhDtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FacilityT__campu__46E78A0C");

            entity.HasOne(d => d.FacilityTypeThanhDt).WithMany(p => p.FacilityThanhDts)
                .HasForeignKey(d => d.FacilityTypeThanhDtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FacilityT__facil__45F365D3");
        });

        modelBuilder.Entity<FacilityTypeThanhDt>(entity =>
        {
            entity.HasKey(e => e.FacilityTypeThanhDtid).HasName("PK__Facility__305648EA43EEAE7A");

            entity.ToTable("FacilityTypeThanhDT");

            entity.Property(e => e.FacilityTypeThanhDtid).HasColumnName("facilityTypeThanhDTID");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("createDate");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("typeName");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("datetime")
                .HasColumnName("updateDate");
        });

        modelBuilder.Entity<FacilityUnitKietNt>(entity =>
        {
            entity.HasKey(e => e.FacilityUnitKietNtId).HasName("PK__Facility__F2BBAEBE28ECB0CE");

            entity.ToTable("FacilityUnitKietNT");

            entity.Property(e => e.FacilityUnitKietNtId).HasColumnName("facilityUnitKietNT_id");
            entity.Property(e => e.Capacity)
                .HasDefaultValue(0)
                .HasColumnName("capacity");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.FacilityThanhDtid).HasColumnName("facilityThanhDTID");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(500)
                .HasColumnName("image_url");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.LastMaintenanceDate)
                .HasColumnType("datetime")
                .HasColumnName("last_maintenance_date");
            entity.Property(e => e.RequiresApproval)
                .HasDefaultValue(false)
                .HasColumnName("requires_approval");
            entity.Property(e => e.UnitName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("unit_name");

            entity.HasOne(d => d.FacilityThanhDt).WithMany(p => p.FacilityUnitKietNts)
                .HasForeignKey(d => d.FacilityThanhDtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FacilityU__facil__4E88ABD4");
        });

        modelBuilder.Entity<MaintenanceRequestMinhTq>(entity =>
        {
            entity.HasKey(e => e.RequestMinhTqId).HasName("PK__Maintena__7A93FA3F48952E32");

            entity.ToTable("MaintenanceRequestMinhTQ");

            entity.Property(e => e.RequestMinhTqId).HasColumnName("requestMinhTQ_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.FacilityUnitKietNtId).HasColumnName("facilityUnitKietNT_id");
            entity.Property(e => e.IsResolved)
                .HasDefaultValue(false)
                .HasColumnName("is_resolved");
            entity.Property(e => e.IssueDescription).HasColumnName("issue_description");
            entity.Property(e => e.ReportedBy).HasColumnName("reported_by");
            entity.Property(e => e.RequestTime)
                .HasColumnType("datetime")
                .HasColumnName("request_time");
            entity.Property(e => e.ResolvedTime)
                .HasColumnType("datetime")
                .HasColumnName("resolved_time");
            entity.Property(e => e.SeverityLevel).HasColumnName("severity_level");
            entity.Property(e => e.TechnicianNote).HasColumnName("technician_note");

            entity.HasOne(d => d.FacilityUnitKietNt).WithMany(p => p.MaintenanceRequestMinhTqs)
                .HasForeignKey(d => d.FacilityUnitKietNtId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maintenan__facil__619B8048");

            entity.HasOne(d => d.ReportedByNavigation).WithMany(p => p.MaintenanceRequestMinhTqs)
                .HasForeignKey(d => d.ReportedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Maintenan__repor__628FA481");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__760965CC150D3D21");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<UsageReportHuyDk>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__UsageRep__779B7C58A1AF4A38");

            entity.ToTable("UsageReportHuyDK");

            entity.Property(e => e.ReportId).HasColumnName("report_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.FacilityUnitKietNtId).HasColumnName("facilityUnitKietNT_id");
            entity.Property(e => e.GeneratedBy).HasColumnName("generated_by");
            entity.Property(e => e.IsFinal)
                .HasDefaultValue(false)
                .HasColumnName("is_final");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.ReportPeriod)
                .HasMaxLength(50)
                .HasColumnName("report_period");
            entity.Property(e => e.TotalBookings).HasColumnName("total_bookings");
            entity.Property(e => e.UsageHours).HasColumnName("usage_hours");
            entity.Property(e => e.UsageRate).HasColumnName("usage_rate");

            entity.HasOne(d => d.FacilityUnitKietNt).WithMany(p => p.UsageReportHuyDks)
                .HasForeignKey(d => d.FacilityUnitKietNtId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsageRepo__facil__6754599E");

            entity.HasOne(d => d.GeneratedByNavigation).WithMany(p => p.UsageReportHuyDks)
                .HasForeignKey(d => d.GeneratedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsageRepo__gener__68487DD7");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__B9BE370F18561DF6");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__AB6E61642200989F").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("full_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.RoleId).HasColumnName("role_id");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__User__role_id__3B75D760");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}